sudo: required
services:
  - docker

before_install:
  - docker build -t rsarode/docker_and_kubernetes -f Dockerfile.dev frontend/ 

script:
  - docker run -e CI=true rsarode/docker_and_kubernetes npm run test